# Outgoing email settings

production:    
  delivery_method: :smtp
  smtp_settings:
    address: smtp.gmail.com
    port: 587
    domain: praexis.com
    authentication: :login
    user_name: "mailer@praexis.com"
    password: "!SvnTrac"
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: "smtp.gmail.com"
    port: 587
    domain: "praexis.com"
    authentication: :login
    user_name: "mailer@praexis.com"
    password: "!SvnTrac"
