# Emailer Configuration Parameters
#
# These parameters are broken out by multiple projects where each project name is the main node.
#
# email_server -- The email server name;  This plugin currently only supports IMAP;  e.g. imap.gmail.com
# email_login -- The login name of the user which this tool will use to retrieve emails;
# email_password -- The password of the above login
# email_port -- The port the email server uses;  (Gmail uses port 993)
# email_folder -- The folder name you would like your email messages retrieved from;
# use_ssl -- If your email server requires you to use ssl to retrieve messages;
#
# THIS IS AN EXAMPLE.  REPLACE THIS WITH YOUR REAL SERVER DATA AND COPY TO: {RAILS_ROOT}/config DIRECTORY
# OF YOUR CORE REDMINE PROJECT.

mindbites:
    email_server: imap.gmail.com
    email_login: jim@praexis.com
    email_password: BigLeague!
    email_port: 993
    email_folder: mindbites
    use_ssl: true
